#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
import serial

s = serial.Serial()
s.baudrate = 9600
s.timeout = 0
s.port = "/dev/ttyAMA0"


try:
    s.open()
except serial.SerialException, e:
    sys.stderr.write("could not open port %r: %s\n" % (s.port, e))
    sys.exit(1)
print "Serial port ready"



def soleil():
    """Permet l'apparition d'un soleil sur le Pi-lite pour indiquer que la météo est ensoleillée."""
    s.write("$$$ALL,OFF\r")
    s.write("$$$P2,5,ON\r")
    s.write("$$$P3,1,ON\r")
    s.write("$$$P3,5,ON\r")
    s.write("$$$P3,9,ON\r")
    s.write("$$$P4,2,ON\r")
    s.write("$$$P4,5,ON\r")
    s.write("$$$P4,8,ON\r")
    s.write("$$$P6,4,ON\r")
    s.write("$$$P6,5,ON\r")
    s.write("$$$P6,6,ON\r")
    s.write("$$$P7,1,ON\r")
    s.write("$$$P7,2,ON\r")
    s.write("$$$P7,4,ON\r")
    s.write("$$$P7,5,ON\r")
    s.write("$$$P7,6,ON\r")
    s.write("$$$P7,8,ON\r")
    s.write("$$$P7,9,ON\r")
    s.write("$$$P8,4,ON\r")
    s.write("$$$P8,5,ON\r")
    s.write("$$$P8,6,ON\r")
    s.write("$$$P10,2,ON\r")
    s.write("$$$P10,5,ON\r")
    s.write("$$$P10,8,ON\r")
    s.write("$$$P11,1,ON\r")
    s.write("$$$P11,5,ON\r")
    s.write("$$$P11,9,ON\r")
    s.write("$$$P12,5,ON\r")
    time.sleep(4)
    s.write("$$$ALL,OFF")

def pluie():
    """Permet l'apparition de pluie sur le Pi-lite pour indiquer que la météo est pluvieuse."""
    s.write("$$$ALL,OFF\r")
    s.write("$$$P1,1,ON\r")
    s.write("$$$P2,1,ON\r")
    s.write("$$$P3,1,ON\r")
    s.write("$$$P4,1,ON\r")
    s.write("$$$P5,1,ON\r")
    s.write("$$$P6,1,ON\r")
    s.write("$$$P7,1,ON\r")
    s.write("$$$P8,1,ON\r")
    s.write("$$$P9,1,ON\r")
    s.write("$$$P10,1,ON\r")
    s.write("$$$P11,1,ON\r")
    s.write("$$$P12,1,ON\r")
    s.write("$$$P13,1,ON\r")
    s.write("$$$P14,1,ON\r")
    s.write("$$$P3,2,ON\r")
    s.write("$$$P4,2,ON\r")
    s.write("$$$P5,2,ON\r")
    s.write("$$$P6,2,ON\r")
    s.write("$$$P7,2,ON\r")
    s.write("$$$P8,2,ON\r")
    s.write("$$$P9,2,ON\r")
    s.write("$$$P10,2,ON\r")
    s.write("$$$P11,2,ON\r")
    s.write("$$$P12,2,ON\r")
    s.write("$$$P4,1,ON\r")
    s.write("$$$P3,3,ON\r")
    s.write("$$$P2,5,ON\r")
    s.write("$$$P1,7,ON\r")
    s.write("$$$P4,7,ON\r")
    s.write("$$$P3,9,ON\r")
    s.write("$$$P5,5,ON\r")
    s.write("$$$P6,3,ON\r")
    s.write("$$$P7,1,ON\r")
    s.write("$$$P6,9,ON\r")
    s.write("$$$P7,7,ON\r")
    s.write("$$$P8,5,ON\r")
    s.write("$$$P9,3,ON\r")
    s.write("$$$P10,1,ON\r")
    s.write("$$$P9,9,ON\r")
    s.write("$$$P10,7,ON\r")
    s.write("$$$P11,5,ON\r")
    s.write("$$$P12,3,ON\r")
    s.write("$$$P13,1,ON\r")
    time.sleep(4)
    s.write("$$$ALL,OFF\r")

def nuage():
    
    """Permet l'apparition d'un nuage sur le Pi-lite pour indiquer que la météo est nuageuse."""
    s.write("$$$ALL,OFF")
    s.write("$$$P5,3,ON\r")
    s.write("$$$P5,3,ON\r")
    s.write("$$$P6,3,ON\r")
    s.write("$$$P7,3,ON\r")
    s.write("$$$P8,3,ON\r")
    s.write("$$$P9,3,ON\r")
    s.write("$$$P4,4,ON\r")
    s.write("$$$P5,4,ON\r")
    s.write("$$$P6,4,ON\r")
    s.write("$$$P7,4,ON\r")
    s.write("$$$P8,4,ON\r")
    s.write("$$$P9,4,ON\r")
    s.write("$$$P10,4,ON\r")
    s.write("$$$P3,5,ON\r")
    s.write("$$$P4,5,ON\r")
    s.write("$$$P5,5,ON\r")
    s.write("$$$P6,5,ON\r")
    s.write("$$$P7,5,ON\r")
    s.write("$$$P8,5,ON\r")
    s.write("$$$P9,5,ON\r")
    s.write("$$$P10,5,ON\r")
    s.write("$$$P11,5,ON\r")
    s.write("$$$P4,6,ON\r")
    s.write("$$$P5,6,ON\r")
    s.write("$$$P6,6,ON\r")
    s.write("$$$P7,6,ON\r")
    s.write("$$$P8,6,ON\r")
    s.write("$$$P9,6,ON\r")
    s.write("$$$P10,6,ON\r")
    s.write("$$$P5,7,ON\r")
    s.write("$$$P6,7,ON\r")
    s.write("$$$P7,7,ON\r")
    s.write("$$$P8,7,ON\r")
    s.write("$$$P9,7,ON\r")
    time.sleep(4)
    s.write("$$$ALL,OFF\r")
